### ISSUE TITLE
Windows based Simulink

### ISSUE THREAD

**Issue by ishikawajp** [worldwidemv/SimulinkBlock_RehaMove3#3]
I would like to use the RehaMove3 by using Simulink on OS: Windows.  How do I modify the your SimulinkBlock files.
The Soft-Realtime Simulink Toolbox seems to be worked on only Linux. 
Please tell me the idea or advice.

**Comment by worldwidemv** [comment]
Hello,

I am not sure if you need to change anything in the block, but I guess pthread might be Linux / POSIX specific.

However, you already saw, that the Soft-Realtime Simulink toolbox is the real problem, specificity the _ert\_linux_ part of the toolbox.
This toolbox is needed to compile a native executable from Simulink diagram using high priority and high precision timers to generate the fixed sample time of the Simulink diagram.  
This is obviously different under Windows than it is for Linux.  
A second problem is the compilation process, because the compiler toolchain installation is much more difficult under Windows as under Linux/MacOS, so I have heard.

Anyway, we had a student project, that implemented a first test of a Windows implementation. Unfortunately the project was never really finished, but I have attached there code, so maybe you can get it running....

[ert_windows.zip](https://github.com/worldwidemv/SimulinkBlock_RehaMove3/files/5030182/ert_windows-master-94445464699eeeda9660b71efc76f5a081ce78b7.zip)

**Comment by ishikawajp** [comment]
Thank you. I hope that the student project will be successful. 
I have tried to build the s-function block of RehaMove3. However, it is difficult to solve the the error with respect to the Soft-Realtime Simulink toolbox. 
Now, I try to use the Real Time sync instead of Realtime Simulink toolbox as the same as RehaStim1. Real Time sync is can be used by normal mode. Have you ever considered the Real Time sync ?

**Comment by nonlinearcontrols** [comment]
Hello, I am also interested in getting a Windows version of ScienceMode3

**Comment by sam-hagh** [comment]
Same here, I'd also be interested in a Windows-compatible version of the block.
